version: 2
updates:
  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 5

  # Frontend (Node.js / npm) dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:30"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "npm"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
      major:
        update-types:
          - "major"
      eslint:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "eslint-*"
          - "eslint-plugin-*"
          - "eslint-config-*"
          - "eslint-plugin-react*"
          - "eslint-plugin-react-hooks*"
          - "eslint-plugin-react-refresh*"
      test-and-types:
        patterns:
          - "jest*"
          - "@testing-library/*"
          - "typescript"
          - "@types/*"
          - "ts-jest*"
          - "babel-jest*"
          - "identity-obj-proxy*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
          - "typescript-eslint"

  # Backend (Python / pip) dependencies
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "python"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"
    versioning-strategy: "increase-if-necessary"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
      major:
        update-types:
          - "major"
