version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev.backend
    ports:
      - "8001:8001"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - backend_cache:/opt/cache
    networks:
      - lyrics-dev
    command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8001", "--log-level", "debug"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev.frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_BACKEND_URL=http://localhost:8001
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - frontend_cache:/app/.vite
    networks:
      - lyrics-dev
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    restart: unless-stopped
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

networks:
  lyrics-dev:
    driver: bridge
    name: lyrics-dev-network

volumes:
  backend_cache:
    driver: local
  frontend_cache:
    driver: local
